### ISSUE TITLE
Error pushing data to databox api

### ISSUE THREAD

**Issue by seanforyou23** [databox/databox-js#11]
Hello! I'm trying to push a dataset to databox api, and receiving the following error

```sh
ERROR pushing LEADS datablock data to databox api
{ type: 'entity.too.large', message: 'Request entity too large.' }
```

<img width="471" alt="Screen Shot 2020-10-22 at 12 59 45 PM" src="https://user-images.githubusercontent.com/5942899/96905707-cfc5d280-1466-11eb-8c6c-0098d7183854.png">

Can you help me understand where I can find documentation around such limits? I suppose I need to chunk this out, but what's the maximum limit? Sorry if I've overlooked something! Thank you!

**Comment by VladaPetrovic** [comment]
Hi @seanforyou23!
The payload size limit is 500Kb. 
You are right. There is no reference for this limit in the documentation. We'll update it.

**Comment by VladaPetrovic** [comment]
Here is a useful help article [How to sync custom data with Databox](https://help.databox.com/article/171-how-to-sync-custom-data-with-databox#guidelines) that also mentions payload size limitation.
