### ISSUE TITLE
Server returns ERROR  on PUSH  when certain UNICODE characters are in the request contents.

### ISSUE THREAD

**Issue by colxi** [databox/databox-js#7]
You can reproduce the error response, inserting some extended UNICODE characters in the values of the attributes ,  and calling to the Databox.prototype.push() method  .
I could consider this limitation a big issue for non english speakeing communites.
In my case, as a Spanish speaker, and considering that almost the 20% of our words  have an accent (á é í ó ú) , this makes it unusable.

Proposed test characters: 
- 焦 (chinese)
- ñ (spanish)
- ö (french)
- ç (catalan)

Test code:
```
databoxClient.push({
        key     :'test',
        value   : 1,
        attributes : {
            crash : 'á',
        }
    }, response => console.log(response) );
```
Server Response:
`Object {type: "invalid_json", message: "Invalid request body - JSON parse error"}`

**Comment by colxi** [comment]
I fixed this issue, and opened a PULL request : #6

**Comment by VladaPetrovic** [comment]
Thanks for reporting the issue and providing the fix @colxi 👍 
I need to validate it against the server and confirm that it's only sdk issue.
